### ISSUE TITLE
Fix merge conflicts as introduced previously

### ISSUE THREAD

**Issue by pschmied** [pschmied/do-some-things-in-js#10]
#9 likely caused a merge conflict.

DON'T PANIC

As the one who encounters the merge conflict, you have to fix it. But you also get to decide how it gets fixed. So... rock and roll.

Some hints:
 - you'll need to "pull" the offending changes from the remote repo on github to be able to merge
 - there are fancy graphical diffing utilities, but you should probably also know how to open a text editor and see the stuff git adds to show you where conflicts are, and also understand that you simply have to make the conflicted file look like you want.
 - Once your file looks like you want, commit it and push it per normal.

**Comment by gricha2380** [comment]
Done and dusted.
