### ISSUE TITLE
Javascript calisthenics

### ISSUE THREAD

**Issue by pschmied** [pschmied/do-some-things-in-js#11]
Create a javascript collection (or generating function) that contains all integers in the range 0-99999.

Create a function that will, when given the input created above, return the sum of all odd integers in the collection.

Put this code in a file in an appropriately named directory with a readme explaining how the hell I run your code. ;-)

**Comment by gricha2380** [comment]
https://github.com/pschmied/do-some-things-in-js/tree/gh-pages
